# Generated by Django 5.2.8 on 2025-11-30 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('is_chain', models.BooleanField(default=False)),
                ('chain', models.ForeignKey(blank=True, db_column='chain_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
    ]
