# Generated by Django 5.2.8 on 2025-12-04 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('expire_date', models.DateField()),
                ('is_expired', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('is_distributed', models.BooleanField(default=False)),
                ('donation', models.ForeignKey(db_column='donation_id', on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='donation.donation')),
            ],
            options={
                'db_table': 'fooditem',
                'ordering': ['food_id'],
            },
        ),
    ]
