"""Add category field to FoodItem

Generated by assistant to match model changes.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fooditem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="category",
            field=models.CharField(blank=True, choices=[('Vegan', 'Vegan'), ('Islamic', 'Islamic')], max_length=32, null=True),
        ),
    ]
