# Generated by Django 5.2.8 on 2025-12-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooditem', '0002_add_category'),
        ('fooditem', '0002_fooditem_chain'),
    ]

    operations = [
    ]
