# Generated by Django 5.2.8 on 2025-12-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('capacity', models.FloatField()),
                ('stored_date', models.DateField()),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
