# Generated by Django 5.2.8 on 2025-12-04 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_alter_community_warehouse_id_delete_warehouse'),
        ('donation', '0001_initial'),
        ('users', '0002_remove_recipient_community_id_recipient_community'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('delivery_type', models.CharField(choices=[('donation', 'Donation'), ('distribution', 'Distribution')], max_length=20)),
                ('pickup_time', models.DateTimeField()),
                ('dropoff_time', models.DurationField()),
                ('pickup_location_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('warehouse', 'Warehouse')], max_length=20)),
                ('dropoff_location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('community', 'Community')], max_length=20)),
                ('community_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='community.community')),
                ('donation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='donation.donation')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='users.user')),
                ('warehouse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='warehouse.warehouse')),
            ],
        ),
    ]
