# Generated by Django 5.2.8 on 2025-12-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_add_request_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='request_item',
        ),
    ]
