# Generated by Django 5.2.8 on 2025-12-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_delivery_request_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivered_quantity',
        ),
    ]
