# Generated by Django 5.2.8 on 2025-12-15 05:19

from django.db import migrations, models


def convert_time_to_datetime(apps, schema_editor):
    """Convert existing time values to datetime using pickup_time as base date"""
    if schema_editor.connection.vendor != "postgresql":
        return
    
    # Step 1: Add a temporary column with timestamp type
    schema_editor.execute(
        """
        ALTER TABLE delivery_delivery 
        ADD COLUMN dropoff_time_temp TIMESTAMP;
        """
    )
    
    # Step 2: Convert time to datetime by combining with pickup_time date
    schema_editor.execute(
        """
        UPDATE delivery_delivery
        SET dropoff_time_temp = (pickup_time::date + dropoff_time::time)::timestamp
        WHERE dropoff_time IS NOT NULL AND pickup_time IS NOT NULL;
        """
    )
    
    # Step 3: Set default for NULL values (use pickup_time or current timestamp)
    schema_editor.execute(
        """
        UPDATE delivery_delivery
        SET dropoff_time_temp = COALESCE(pickup_time, CURRENT_TIMESTAMP)
        WHERE dropoff_time_temp IS NULL;
        """
    )
    
    # Step 4: Drop the old column
    schema_editor.execute(
        """
        ALTER TABLE delivery_delivery 
        DROP COLUMN dropoff_time;
        """
    )
    
    # Step 5: Rename the temp column to the original name
    schema_editor.execute(
        """
        ALTER TABLE delivery_delivery 
        RENAME COLUMN dropoff_time_temp TO dropoff_time;
        """
    )


def reverse_convert_datetime_to_time(apps, schema_editor):
    """Reverse: extract time from datetime"""
    if schema_editor.connection.vendor != "postgresql":
        return
    
    # Add temporary time column
    schema_editor.execute(
        """
        ALTER TABLE delivery_delivery 
        ADD COLUMN dropoff_time_temp TIME;
        """
    )
    
    # Extract time from datetime
    schema_editor.execute(
        """
        UPDATE delivery_delivery
        SET dropoff_time_temp = dropoff_time::time
        WHERE dropoff_time IS NOT NULL;
        """
    )
    
    # Drop datetime column
    schema_editor.execute(
        """
        ALTER TABLE delivery_delivery 
        DROP COLUMN dropoff_time;
        """
    )
    
    # Rename temp column
    schema_editor.execute(
        """
        ALTER TABLE delivery_delivery 
        RENAME COLUMN dropoff_time_temp TO dropoff_time;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_merge_20251215_1048'),
    ]

    operations = [
        migrations.RunPython(convert_time_to_datetime, reverse_convert_datetime_to_time),
        migrations.AlterField(
            model_name='delivery',
            name='dropoff_time',
            field=models.DateTimeField(),
        ),
    ]
