# Generated by Django 5.2.8 on 2025-12-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_change_dropoff_time_to_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='List of food items and quantities being delivered'),
        ),
    ]
