# Generated by Django 5.2.8 on 2025-12-15 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_add_items_jsonfield'),
        ('fooditem', '0003_merge_0002_add_category_0002_fooditem_chain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='items',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_quantity',
            field=models.IntegerField(blank=True, help_text='Quantity of food item being delivered', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='food_item',
            field=models.ForeignKey(blank=True, db_column='food_id', help_text='Food item being delivered', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='fooditem.fooditem'),
        ),
    ]
