# Generated by Django 5.2.8 on 2025-12-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_replace_items_with_food_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_quantity',
            field=models.CharField(blank=True, help_text="Quantity of food item being delivered (e.g., '15 kg', '8 bucket')", max_length=50, null=True),
        ),
    ]
