# Generated by Django 5.2.8 on 2025-12-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_change_delivery_quantity_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
