# Generated by Django 5.2.8 on 2025-12-04 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('capacity', models.FloatField()),
                ('stored_date', models.DateField()),
                ('exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('received_time', models.DateTimeField()),
                ('population', models.IntegerField()),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communities', to='community.warehouse')),
            ],
        ),
    ]
