# Generated by Django 5.2.8 on 2025-12-04 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communities', to='warehouse.warehouse'),
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
