# Generated by Django 5.2.8 on 2025-12-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_delivery_request_item'),
        ('donation_request', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestItem',
        ),
    ]
