# Generated by Django 5.2.8 on 2025-12-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_request', '0002_donationrequest_community'),
        ('donation_request', '0003_donationrequest_created_by'),
    ]

    operations = [
    ]
