# Generated by Django 5.2.8 on 2025-12-15 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_request', '0005_remove_donationrequest_created_by'),
        ('users', '0011_add_user_role_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_requests', to='users.user'),
        ),
    ]
