# Generated by Django 5.2.8 on 2025-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_request', '0006_donationrequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
