# Generated by Django 5.2.8 on 2025-12-04 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_community_warehouse_id_delete_warehouse'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='community_id',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recipients',
                to='community.community',
                db_column='community_id',
            ),
        ),
    ]
