# Generated by Django 5.2.8 on 2025-12-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_chain'),
        ('users', '0002_remove_recipient_community_id_recipient_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='restaurant_id',
            field=models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
