# Generated by Django 5.2.8 on 2025-12-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_donor_restaurant_id"),
        ("users", "0003_alter_donor_restaurant_id_alter_user_password"),
    ]

    operations = []
