# Generated by Django 5.2.8 on 2025-12-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_chain'),
        ('users', '0004_merge_20251212_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_roles', to='users.user'),
        ),
        migrations.AlterField(
            model_name='deliverystaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_roles', to='users.user'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_roles', to='users.user'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_roles', to='users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together={('user', 'restaurant_id')},
        ),
    ]
