# Generated by Django 5.2.8 on 2025-12-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_chain'),
        ('users', '0006_unique_role_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(blank=True, db_column='restaurant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
