# Generated by Django 5.2.8 on 2025-12-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_restaurant_fields_to_user'),
        ('users', '0007_user_role_flags'),
    ]

    operations = [
    ]
