# Generated by Django 5.2.8 on 2025-12-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20251214_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_donor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_recipient',
        ),
    ]
