# Generated by Django 5.2.8 on 2025-12-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_recipient_request_fk'),
        ('users', '0009_remove_user_is_donor_remove_user_is_recipient'),
    ]

    operations = [
    ]
